<h2>Soal 1: Membuat Objek DataFrames</h2>

- Buatlah objek dataframes dari objek dictionary, Bebas!

In [1]:
# Membuat dataframes dari dictionary
import pandas as pd
data = {'col_1': [4, 3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd', 'e']}
pd.DataFrame.from_dict(data)

   col_1 col_2
0      4     a
1      3     b
2      2     c
3      1     d
4      0     e

<h2>Soal 2: Membaca data dari file</h2>

Download file bernama [diamonds.csv](https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd), kemudian baca data tersebut dan assign ke dalam suatu variabel kemudian print.

In [2]:
# Membaca data dan memasukannya kedalam suatu variabel
url = 'https://raw.githubusercontent.com/azkamuhamco/sanbercode/master/diamonds-1.csv'
df1 = pd.read_csv(url)
df1

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

Expected Result:

![alt text](https://drive.google.com/uc?id=1BvgM5mJEVfj0fllrjkBfQwn0QIFkry_t)

<h2>Soal 3: DataFrame vs Series</h2>

- Apa perbedaan Series dengan list dan dictionary
- Apa perbedaan dataframe dan series
- Buatlah suatu data series

Jawab: 
<ul>
    <li>Perbedaan Series dengan list dan dictionary</li>
    Series dapat mengatur index, sedangkan list dan dictionary tidak dapat mengatur index. Index pada list dan dictionary berdasarkan urutan data yang dimasukkan
    <br><br><li>Perbedaan dataframe dan series</li>
    Dataframe = Objek dua dimensi => Data bisa terdiri dari banyak kolom<br>
    Series = Objek satu dimensi => Data hanya bisa satu kolom
</ul>

In [3]:
# code here
x = pd.Series([16,23,34,46,58], index=['o', 'p', 'q', 'r', 's'])
x

o    16
p    23
q    34
r    46
s    58
dtype: int64

<h2>Soal 4: Pemeriksaan Data Sederhana</h2>

Di soal no 2 kamu telah membaca data tentang diamonds. pada soal ini cobalah suatu metode dari pandas untuk mengetahui beberapa data pertama dan beberapa data terakhir. kemudian sebutkan nilai dari:
- baris pertama dari column price
- baris terakhir dari column color

tunjukan cara kalian menemukan nilai tersebut di block di bawah ini.

In [4]:
# code here
print("Nilai dari baris pertama dari column price ="+ df1['price'].head(1).to_string(index=False))
print("Nilai dari baris terakhir dari column color ="+ df1['color'].tail(1).to_string(index=False))

Nilai dari baris pertama dari column price = 326
Nilai dari baris terakhir dari column color = D

<h2>Soal 5: Deskriptif Statistik</h2>

Jelaskan apa itu deskriptif statistik!

Jawab: Statistika deskriptif merupakan suatu metode yang berhubungan dengan pengumpulan atau penyajian data sampai memberi informasi yang berguna

<h2>Soal 6: Practice Deskriptif Statistik</h2>

- Gunakan suatu metode dari pandas untuk mengetahui deskriptif statistik dari suatu data
- Berapa nilai rata-rata dari column price
- Berapa nilai standar deviasi dari column depth
- Berapa nilai maximum dari column carat

In [5]:
# code here
print("rata-rata dari column price =", df1['price'].mean())
print("standar deviasi dari column depth =", df1['depth'].std())
print("nilai max dari column carat =", df1['carat'].max())

rata-rata dari column price = 3932.799721913237
standar deviasi dari column depth = 1.4326213188337733
nilai max dari column carat = 5.01